INSERT OR REPLACE INTO clients (id, tipe, perusahaan, provinsi, kota, area, alamat_detail, garis_lintang, garis_bujur, telepon_kantor, email_kantor, nama_penanggung_jawab, jabatan, no_hp, catatan, status_kemitraan, id_penjual, nama_penjual, value_kompetitor, list_produk_kompetitor) VALUES 
('D001', 'Distributor', 'PT Distribusi Mandiri', 'DKI Jakarta', 'Jakarta Utara', 'Kawasan Industri Pulo Gadung', 'Jl. Raya Jatinegara Timur No. 15', -6.1384, 106.8643, '021-5551234', 'office.alincorporation@gmail.com', 'Joko Susilo', 'Direktur Operasional', '081999888777', 'Kapasitas gudang besar untuk printer dan laptop', 'Mitra Aktif', 'S001', 'Andi Pratama', NULL, NULL),
('D002', 'Distributor', 'CV Mitra Hardware', 'DKI Jakarta', 'Jakarta Timur', 'Kawasan Industri Cakung', 'Jalan Pegangsaan Dua Blok A1', -6.23, 106.9, '021-5559876', 'mitra@hardware.co.id', 'Susanti', 'Manager Pembelian', '081888777666', 'Distribusi wilayah Jakarta Timur', 'Target', 'S002', 'Budi Santoso', 'Logitech memiliki brand awareness yang lebih agresif di sektor UMKM. Saat ini kita sedang approach dengan solusi Poly untuk enterprise mereka.', json('["Logitech", "Jabra"]')),
('D003', 'Distributor', 'PT Global Sarana', 'DKI Jakarta', 'Jakarta Selatan', '', 'Gedung Cyber 2, Jl. HR Rasuna Said X5', -6.24, 106.82, '021-5555678', 'cs@globalsarana.com', 'Hendra Pratama', 'VP Operations', '081777666555', 'Fokus pada Poly system untuk conference', 'Calon Mitra', 'S003', 'Citra Lestari', 'Pihak mereka masih sering deal dengan Lenovo karena support garansi onsite yg memuaskan, saat ini mencoba switch ke HP Inc karena stok line-up lebih lengkap.', json('["Lenovo", "Dell", "Epson"]')),
('E001', 'End User', 'PT Solusi Jaya Mandiri', 'DKI Jakarta', 'Jakarta Pusat', 'Kawasan Perkantoran Thamrin', 'Menara Prima Lt 12, Jl. MH Thamrin No. 8', -6.1834, 106.8227, '021-33445566', 'procurement@solusijaya.co.id', 'Dedi Setiawan', 'IT Manager', '085566778899', 'Perusahaan swasta, kebutuhan laptop & PC setahun sekali', 'Mitra Aktif', 'S001', 'Andi Pratama', NULL, NULL),
('E002', 'End User', 'Rizki Personal (Freelancer)', 'Jawa Barat', 'Bandung', 'Dago', 'Jl. Ir. H. Juanda No. 100', -6.8906, 107.6131, '-', 'rizki.freelance@gmail.com', 'Rizki Ramadhan', 'Personal', '081233445566', 'Kreator konten, butuh workstation tangguh', 'Calon Mitra', 'S002', 'Budi Santoso', 'Tertarik dengan Apple ekosistem karena gengsi dan Airdrop, budget masih memungkinkan untuk ditawari produk workstation kita.', json('["Apple", "Asus"]')),
('S001', 'Sales', 'PT Teknologi Maju', 'DKI Jakarta', 'Jakarta Selatan', 'SCBD', 'Gedung Equity Tower Lt 15, Jl. Jend Sudirman Kav 52-53', -6.2272, 106.8066, '021-12345678', 'info@teknologimaju.co.id', 'Andi Pratama', 'Sales Enterprise', '081234567890', 'Fokus pada pengadaan corporate', NULL, NULL, NULL, NULL, NULL),
('S002', 'Sales', 'CV Solusi Digital', 'DKI Jakarta', 'Jakarta Pusat', '', 'Ruko Cideng Timur No 88', -6.1824, 106.8277, '021-98765432', 'contact@solusidigital.com', 'Budi Santoso', 'Senior Sales', '081298765432', 'Klien mayoritas startup', NULL, NULL, NULL, NULL, NULL),
('S003', 'Sales', 'PT Nusantara Tech', 'DKI Jakarta', 'Jakarta Barat', 'Kawasan Industri Daan Mogot', 'Kawasan Pesing Polgar Blok E2', -6.1683, 106.7588, '021-11223344', 'halo@nusantaratech.com', 'Citra Lestari', 'Sales Lead', '081345678910', 'Potensial tender pemerintahan', NULL, NULL, NULL, NULL, NULL),
('B001', 'Broker', 'Freelance Broker Indonesia', 'DKI Jakarta', 'Jakarta Timur', 'Cawang', 'Jalan MT Haryono No. 12', -6.2425, 106.8681, '021-5551234', 'contact@brokerindo.com', 'Dedi Sukandar', 'Freelance Broker', '081555666777', 'Koneksi ke perusahaan multinasional', NULL, NULL, NULL, NULL, NULL);
